version: "3.9"

services:

  mysql_readonly_service:
    image: mysql:5.7
    container_name: java_springboot_reactive_api_exemple_mysql_service
    ports:
      - 3306:3306
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/createreadonlyuser.sql:/docker-entrypoint-initdb.d/2.sql"
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dumb_db
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 10